### PR TITLE
add descriptions to the onehot_ function

### PR DESCRIPTION
**Pull request by 4may**

### CODE REVIEW

**Comment by rasbt** [comment]
Sorry, didn't see this PR earlier. Let me have a look at it

**Comment by rasbt** [comment]
Actually, looking at it, this PR looks very useful, adding the missing docstring for the _onehot method. May I ask why you closed it?

**Comment by 4may** [comment]
Thank you for your reviewing. I’m sorry, I misunderstood that my pr was not useful for you.
If there are no problem in my pr, please merge it at your convenience :)

**Comment by 4may** [comment]
I finally had read your book yesterday. It took a month.
It was challenging for me, since I am Japanese and not good at English.
But it was so exciting experience and I’ve learned a lot thanks to your book :)
Thank you!

**Comment by rasbt** [comment]
Sorry about causing this misunderstanding. It's been a very busy semester and I didn't see it earlier. In any case, your contribution is useful indeed, and thanks for the PR. I am also happy to hear that you found the book useful!

**Pull request merged**
