### PR TITLE
for loop fix to follow math formula

### PR DESCRIPTION
**Pull request by elfelround**
for loop not following mathematical formula

### CODE REVIEW

**Comment by vmirly** [comment]
Hi @elfelround ,

thanks for the suggestion. I agree with your suggestion, it is more general. However, I think the division by s should be `(len(x_padded) - len(w_rot) ) / s` so in the suggested change, one parentheses is missing. 

In this function, the assumption is that we are using "same" padding, that's why we also compare with `np.convolve(x, w, mode='same')`. The current formulation in this function would work for any combination of kernel-size and padding-size that results in "same"-padding, for example if kernel has size 3, and padding p=1, the function would still work.

I will discuss it with Sebastian for this change. I appreciate your suggestion. 👍 :

**Comment by elfelround** [comment]
yes, the missing parenthesis is true, i changed the code on my own code but forgot it in here

I wouldnt say it is the assumption of same padding, it is more like a hardcoded magic number, if it was an assumption of same padding it wouldnt allow for padding to be passed upon call but calculate itself

**Comment by elfelround** [comment]
@pep8speaks fixed

**Comment by elfelround** [comment]
@pep8speaks now

**Comment by rasbt** [comment]
Thanks a lot for the PR. I agree with Vahid, your suggestions is closer to the math formula in the book and the more general solution. While the current one (`for i in range(0, int(len(x)/s), s)`) works here, it wouldn't work for settings where `p=0`, for example. Thanks for correcting that!

**Comment by elfelround** [comment]
submitted a packt digital credit request for a pdf upon this and the pickle issue today as erick lestrange. cheers

**Comment by rasbt** [comment]
Just wanted to say thanks again for all the feedback. You have a great eye for detail. We really appreciate it!

**Comment by elfelround** [comment]
@rasbt i have more errata but they are mainly irrelevant typos. crushing on you and your book was really good, enjoyed every bit of it, ure welcome to add me on linkedin if in the future or not both are fine

linkedin.com/in/ericklestrange/
xx

**Comment by rasbt** [comment]
Thanks so much for the kind words! And I am glad to hear that you have a good experience with the book overall! If it is not too much effort to type them up, I'd be great to get a list of these typos. With traditional publishing, it's hard to get things updated retrospectively, but it would be useful in case we are planning a 4th edition one day.

**Pull request merged**
